In [1]:
import pandas as pd
df=pd.read_csv("Desktop\processed_data.csv")

In [2]:
df.head(2)

Unnamed: 0    Age  Gender         Education Country   Ethnicity   Nscore  \
0           1  35_44  Female  ProfessionalCert      UK  WhiteAsian  0.31287   
1           2  25_34    Male         Doctorate      UK       White -0.67825   

    Escore   Oscore   Ascore  ...  Ecstasy  Heroin  Ketamine Legalh  LSD Meth  \
0 -0.57545 -0.58331 -0.91699  ...      CL0     CL0       CL0    CL0  CL0  CL0   
1  1.93886  1.43533  0.76096  ...      CL4     CL0       CL2    CL0  CL2  CL3   

  Mushrooms Nicotine Semer  VSA  
0       CL0      CL2   CL0  CL0  
1       CL0      CL4   CL0  CL0  

[2 rows x 32 columns]

In [3]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
Alcohol_encoded=le.fit_transform(df.Alcohol)
print(Alcohol_encoded)

[5 5 6 ... 4 5 4]


In [4]:
x_data=df.drop(df.columns[[0,1,2,3,4,5,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]],axis=1)

In [6]:
x_data

Nscore   Escore   Oscore   Ascore   Cscore  Impulsive       SS
0     0.31287 -0.57545 -0.58331 -0.91699 -0.00665   -0.21712 -1.18084
1    -0.67825  1.93886  1.43533  0.76096 -0.14277   -0.71126 -0.21575
2    -0.46725  0.80523 -0.84732 -1.62090 -1.01450   -1.37983  0.40148
3    -0.14882 -0.80615 -0.01928  0.59042  0.58489   -1.37983 -1.18084
4     0.73545 -1.63340 -0.45174 -0.30172  1.30612   -0.21712 -0.21575
...       ...      ...      ...      ...      ...        ...      ...
1880 -1.19430  1.74091  1.88511  0.76096 -1.13788    0.88113  1.92173
1881 -0.24649  1.74091  0.58331  0.76096 -1.51840    0.88113  0.76540
1882  1.13281 -1.37639 -1.27553 -1.77200 -1.38502    0.52975 -0.52593
1883  0.91093 -1.92173  0.29338 -1.62090 -2.57309    1.29221  1.22470
1884 -0.46725  2.12700  1.65653  1.11406  0.41594    0.88113  1.22470

[1885 rows x 7 columns]

In [5]:
y_data=Alcohol_encoded

In [6]:
y_data

array([5, 5, 6, ..., 4, 5, 4])

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3,random_state=109)

In [8]:
X_test

Nscore   Escore   Oscore   Ascore   Cscore  Impulsive       SS
922   1.23461 -1.23177 -2.39883 -1.07533 -0.78155    1.29221 -0.21575
204  -0.14882  0.96248  1.24033 -0.01729  0.25953   -0.21712  0.40148
931  -0.24649  0.00332  1.06238  0.59042  2.04506   -0.71126 -0.52593
1805  0.41667 -0.80615 -0.58331  0.13136 -0.40581   -1.37983 -1.54858
1679 -0.46725  0.47617 -1.11902 -0.76096 -0.14277   -0.21712  0.76540
...       ...      ...      ...      ...      ...        ...      ...
803  -0.24649  0.16767 -0.31776 -0.45321 -0.89891    1.29221  0.76540
54    0.04257  1.11406 -0.58331 -1.07533 -1.13788    1.29221  1.22470
1849  0.41667  0.96248 -0.17779 -0.45321  0.75830    0.19268 -0.21575
215   1.60383 -0.30033 -0.71727  1.11406 -0.40581    0.19268  0.07987
1266 -0.05188 -0.43999 -0.45174  1.81866  0.25953   -1.37983 -0.52593

[566 rows x 7 columns]

In [9]:
y_test

array([3, 5, 5, 4, 5, 5, 5, 4, 6, 5, 3, 5, 5, 5, 6, 5, 0, 5, 5, 5, 5, 3,
       4, 6, 6, 5, 4, 5, 4, 5, 4, 6, 5, 5, 5, 2, 6, 5, 6, 5, 3, 6, 4, 6,
       5, 6, 5, 5, 5, 6, 4, 5, 5, 2, 4, 6, 2, 5, 3, 4, 3, 6, 6, 5, 5, 6,
       6, 5, 3, 4, 6, 3, 0, 3, 5, 3, 5, 3, 2, 4, 5, 6, 6, 3, 5, 5, 5, 6,
       3, 5, 2, 5, 5, 4, 5, 3, 3, 5, 3, 4, 6, 5, 6, 5, 5, 5, 4, 4, 5, 5,
       4, 6, 6, 5, 5, 5, 6, 6, 5, 6, 3, 5, 5, 5, 4, 5, 4, 5, 3, 5, 5, 5,
       5, 5, 4, 5, 5, 5, 2, 6, 5, 0, 4, 6, 5, 5, 3, 3, 5, 6, 4, 4, 5, 6,
       3, 5, 5, 5, 1, 6, 5, 5, 4, 5, 3, 1, 4, 6, 0, 3, 5, 1, 5, 5, 5, 5,
       5, 5, 6, 6, 6, 3, 5, 6, 5, 3, 4, 6, 2, 5, 4, 5, 5, 5, 5, 5, 1, 5,
       5, 5, 5, 4, 5, 6, 5, 5, 4, 3, 4, 6, 6, 5, 6, 6, 6, 5, 5, 6, 5, 3,
       1, 6, 3, 3, 4, 5, 4, 5, 5, 3, 5, 5, 5, 5, 3, 5, 3, 3, 6, 5, 4, 5,
       5, 5, 6, 4, 4, 6, 5, 6, 6, 5, 5, 3, 3, 5, 3, 6, 5, 5, 5, 5, 4, 6,
       5, 6, 5, 6, 6, 5, 3, 5, 5, 6, 6, 5, 2, 5, 5, 6, 4, 6, 5, 6, 5, 5,
       5, 3, 6, 1, 6, 4, 5, 6, 5, 3, 4, 3, 5, 6, 6,

In [10]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)

In [11]:
y_pred

array([3, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 6, 5, 4, 5, 5, 5, 5, 5,
       5, 5, 5, 6, 5, 5, 6, 5, 6, 6, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5,
       5, 5, 6, 5, 6, 5, 5, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 5, 5, 5, 6, 5,
       5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 6, 5, 5, 5, 6, 5, 6, 5, 5, 5, 5,
       5, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 5, 6, 5, 5, 4, 5, 5, 5, 5, 5, 5,
       5, 4, 5, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 3, 5, 5, 5,
       5, 5, 6, 6, 5, 6, 6, 5, 5, 5, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6,
       5, 5, 5, 5, 5, 6, 6, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       6, 6, 5, 5, 5, 5, 5, 5, 6, 6, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5,
       5, 6, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 6, 5,
       5, 6, 5, 5, 5, 6, 6, 5, 6, 5, 5, 5, 6, 5, 5, 5, 5, 5, 6, 6, 5, 6,
       5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5,

In [12]:
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.37809187279151946


In [13]:
x_new=[[0.31287,-0.57545,-0.58331,-0.91699,-0.00665,-0.21712,-1.18084]]
y_new= gnb.predict(x_new)
print("X=%s, Predicted=%s" % (x_new[0], y_new[0]))

X=[0.31287, -0.57545, -0.58331, -0.91699, -0.00665, -0.21712, -1.18084], Predicted=5


In [14]:
import numpy as np
(unique,counts)=np.unique(y_pred,return_counts=True)
frequencies = np.asarray((unique, counts)).T
print(frequencies)
    

[[  1   1]
 [  3   3]
 [  4   9]
 [  5 452]
 [  6 101]]


In [15]:
import numpy as np
(unique,counts)=np.unique(y_test,return_counts=True)
frequencies1 = np.asarray((unique, counts)).T
print(frequencies1)

[[  0  12]
 [  1   8]
 [  2  19]
 [  3  71]
 [  4  81]
 [  5 241]
 [  6 134]]
